### ISSUE TITLE
Incorporate Goon-Ling Code as explained inside.

### ISSUE THREAD

**Issue by JakeDaBoss** [JakeDaBoss/Baystation12#21]
When a changeling who has already absorbed several humans is threatened or exposed, they can resort to entering horror form. They become an enormous monster with a host of deadly powers, some of which require DNA, and retain their usual abilities such as toxic spit (or an equivalent power). It is still capable of using human weapons and equipment. The downsides are their inability to wear clothes other than hats and backpacks, the complete abandonment of stealth that it requires, the decrease in movement speed, and that maintaining horror form burns up your DNA stockpile. The AI and cyborgs are free to murder you as a blatant non-human. But who cares? You're a monstrous killing machine!
Name Cooldown DNA Cost Description
Devour N/A N/A The abomination quickly eats whoever they have grabbed aggressively (which they do by default), absorbing their DNA. Conveniently, this ability bypasses the need to remove the victim's headgear as well. Be warned that devouring somebody will destroy all items they had on them. Monkeys cannot be consumed.
Horrific scream 10 seconds 1 DNA The abomination lets out a horrible screech, slowing down all nearby humans and occasionally causing them to drop items. Blocked by ear protection (earmuffs etc).
Maintain form Auto 1 DNA per tick Not an ability per se, but important nonetheless. Abominations automatically expend 1 DNA point every two seconds.
Revert N/A 15 DNA Accomplished by pressing Horror Form again. The abomination takes on a human form once more, sacrificing some DNA points in the process. This weakens it and leaves it temporarily stunned. Abominations automatically revert if they run out of DNA points.
Abominations are tough and very capable fighters. Not only do they regenerate stamina extremely quickly and grab their victims aggressively (allowing for a quick snack), the horror form is also incredibly strong and its punches will do a large amount of damage to people, cyborgs and critters, and can smack them across the room. A single punch can be sufficient to stun an unarmored opponent long enough to devour them. Using the Disarm intent is guaranteed to knock a weapon out of somebody's hands and can also literally 'dis-arm' threats (i.e. chop off their limbs). Shamblers can pry open doors and firedoors, and smash through windows as well as grills.
Abominations are impressively resistant to brute damage, receiving only 20% of the damage. As long as they aren't on fire, they constantly heal their wounds (including spontaneous limb regeneration) and are completely immune to all stuns.

**Comment by BlueNexus** [comment]
This would need to be coded entirely from scratch, as gooncode is closed source.

**Comment by JakeDaBoss** [comment]
Are you shitting me? I'll make it Full Release, then.
